### ISSUE TITLE
What's the License

### ISSUE THREAD

**Issue by pip1998** [jianpu/musje#17]
Good job.
It is almost the only useable **Jianpu** library. But is it free to use?

**Comment by malcomwu** [comment]
Thanks, It began as a toy for me, and I had some fun during the development last year. I would say that it is just good enough for demonstration purposes, yet still a way to be **usable**.

Yes, it is free to use, in MIT license as noted in https://github.com/jianpu/musje/blob/master/LICENSE

You are welcome to contribute and join our facebook group https://www.facebook.com/groups/jp.webapp/
